START TRANSACTION;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `user_profiles`;
DROP TABLE IF EXISTS `sessions`;
DROP TABLE IF EXISTS `user_activity_logs`;
DROP TABLE IF EXISTS `admin`;
DROP TABLE IF EXISTS `users`;

SET FOREIGN_KEY_CHECKS = 1;

COMMIT;
